function monitors = setupSWIPSMonitors(instruments)
    % Function initializing and defining properties of measured values for SWIPS system
    
    % =======================================================================
    % define read functions monitors will call to manipulate instrument output 
    % =======================================================================
    function val = read_caenHVPS(self)
        val = self.parent.lastRead;
    end

    % =======================================================================
    % Define monitors for CAEN HVPS channels
    % =======================================================================
    
    monitors = struct(...
        'voltCh0', monitor('readFunc', @(self) self.parent.lastRead(1), ...
                        'setFunc', @(self,volt) self.parent.setVSet(1,volt), ...
                        'textLabel', 'Channel 0 Voltage', ...
                        'unit', 'V', ...
                        'active', true, ...
                        'formatSpec', '%.1f', ...
                        'group', 'HV', ...
                        'parent', instruments.caen_HVPS1 ...
                        ), ...
        'voltCh1', monitor('readFunc', @(self) self.parent.lastRead(2), ...
                        'setFunc', @(self,volt) self.parent.setVSet(2,volt), ...
                        'textLabel', 'Channel 1 Voltage', ...
                        'unit', 'V', ...
                        'active', true, ...
                        'formatSpec', '%.1f', ...
                        'group', 'HV', ...
                        'parent', instruments.caen_HVPS1 ...
                        ), ...
        'voltCh2', monitor('readFunc', @(self) self.parent.lastRead(3), ...
                        'setFunc', @(self,volt) self.parent.setVSet(3,volt), ...
                        'textLabel', 'Channel 2 Voltage', ...
                        'unit', 'V', ...
                        'active', true, ...
                        'formatSpec', '%.1f', ...
                        'group', 'HV', ...
                        'parent', instruments.caen_HVPS1 ...
                        ), ...
        'voltCh3', monitor('readFunc', @(self) self.parent.lastRead(4), ...
                        'setFunc', @(self,volt) self.parent.setVSet(4,volt), ...
                        'textLabel', 'Channel 3 Voltage', ...
                        'unit', 'V', ...
                        'active', true, ...
                        'formatSpec', '%.1f', ...
                        'group', 'HV', ...
                        'parent', instruments.caen_HVPS1 ...
                        ), ...
        'posAzm', monitor('readFunc', @(self) self.parent.lastRead(1), ...
                        'setFunc', @(self,pos) self.parent.setPosition('Group1',pos), ...
                        'textLabel', 'Azm Angle', ...
                        'unit', 'deg', ...
                        'active', true, ...
                        'formatSpec', '%.3f', ...
                        'group', 'position', ...
                        'parent', instruments.newportStage ...
                        ), ...
        'posLin', monitor('readFunc', @(self) self.parent.lastRead(2), ...
                        'setFunc', @(self,pos) self.parent.setPosition('Group2',pos), ...
                        'textLabel', 'Y Position', ...
                        'unit', 'mm', ...
                        'active', true, ...
                        'formatSpec', '%.3f', ...
                        'group', 'position', ...
                        'parent', instruments.newportStage ...
                        ), ...
        'posElv', monitor('readFunc', @(self) self.parent.lastRead(3), ...
                        'setFunc', @(self,pos) self.parent.setPosition('Group3',pos), ...
                        'textLabel', 'Elv. Angle', ...
                        'unit', 'deg', ...
                        'active', true, ...
                        'formatSpec', '%.3f', ...
                        'group', 'position', ...
                        'parent', instruments.newportStage ...
                        ), ...
        'dateTime', monitor('readFunc', @(x) datetime(now(), 'ConvertFrom', 'datenum'), ...
                        'textLabel', 'Date Time', ...
                        'unit', 'D-M-Y H:M:S', ...
                        'parent', struct("Type", 'local', 'Connected', true), ...
                        'formatSpec', "%s" ...
                        ), ...
        'T', monitor('readFunc', @(x) now(), ...
                        'textLabel', 'Time', ...
                        'unit', 'DateNum', ...
                        'parent', struct("Type", 'local', 'Connected', true), ...
                        'formatSpec', "%d" ...
                        ) ...
    );

    % Assign tags to monitors
    fields = fieldnames(monitors);
    for i = 1:numel(fields)
        monitors.(fields{i}).setfield('Tag', fields{i});
    end
end
