classdef beamlineGUI < handle
    %BEAMLINEGUI Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        Hardware
        TestSequence double
        TestDate string
        DataDir string
        TestOperator string
        GasType string
        AcquisitionType string
        hFigure
        hStatusGrp
        hExtractionText
        hExtractionReadText
        hExtractionReadField
        hEinselText
        hEinselReadText
        hEinselReadField
        hExbText
        hExbReadText
        hExbReadField
        hExbSetText
        hExbSetField
        hExbSetBtn
        hEsaText
        hEsaReadText
        hEsaReadField
        hEsaSetText
        hEsaSetField
        hEsaSetBtn
        hDeflText
        hDeflReadText
        hDeflReadField
        hDeflSetText
        hDeflSetField
        hDeflSetBtn
        hYsteerText
        hYsteerReadText
        hYsteerReadField
        hYsteerSetText
        hYsteerSetField
        hYsteerSetBtn
        hFaradayText
        hFaradayReadText
        hFaradayReadField
        hMassText
        hMassReadText
        hMassReadField
        hMassSetText
        hMassSetField
        hMassSetBtn
        hP1Text
        hP1ReadText
        hP1ReadField
        hP2Text
        hP2ReadText
        hP2ReadField
        hP3Text
        hP3ReadText
        hP3ReadField
        hP4Text
        hP4ReadText
        hP4ReadField
        hP5Text
        hP5ReadText
        hP5ReadField
        hFileMenu
        hSequenceText
        hSequenceEdit
        hDateText
        hDateEdit
        hOperatorText
        hOperatorEdit
        OperatorList cell = {'Jonathan Bower','Daniel Abel','Skylar Vogler','Colin van Ysseldyk','Philip Valek','Nathan Schwadron','Zack Smith','David Heirtzler'}
        hGasText
        hGasEdit
        GasList cell = {'Air','Argon','Nitrogen','Helium','Deuterium','Oxygen','Magic gas'}
        hAcquisitionText
        hAcquisitionEdit
        AcquisitionList cell = {'Faraday cup vs ExB sweep'}
        hRunBtn
    end
    
    methods
        function obj = beamlineGUI
            %BEAMLINEGUI Construct an instance of this class
            %   Detailed explanation goes here

            obj.genTestSequence;

%             obj.gatherHardware;

            obj.createGUI;

        end

    end

    methods (Access = private)

        function genTestSequence(obj)

            obj.TestSequence = round(now*1e6);
            obj.TestDate = datestr(obj.TestSequence/1e6,'mmm dd, yyyy HH:MM:SS');
            obj.DataDir = fullfile("C:\data",num2str(obj.TestSequence));
            if ~exist(obj.DataDir,'dir')
                mkdir(obj.DataDir);
            end

        end
        
        function gatherHardware(obj)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            obj.Hardware = initializeInstruments;
        end

        function createGUI(obj)

            obj.hFigure = figure('MenuBar','none',...
                'ToolBar','none',...
                'Resize','off',...
                'Position',[100,100,900,480],...
                'NumberTitle','off',...
                'Name','Beamline GUI');

            obj.hStatusGrp = uipanel(obj.hFigure,...
                'Title','Beamline Status',...
                'FontWeight','bold',...
                'FontSize',12,...
                'Units','pixels',...
                'Position',[40,40,480,420]);

            ysize = 22;
            ygap = 6;
            ystart = 360;
            ypos = ystart;
            xgap = 20;
            xstart = 10;
            xpos = xstart;
            xsize = 80;

            obj.hExtractionText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Extraction',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hEinselText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Einsel',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hExbText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','ExB',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hEsaText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','ESA',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hDeflText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Defl',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hYsteerText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','y-steer',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hFaradayText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Faraday cup',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hMassText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Mass flow',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP1Text = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure 1',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP2Text = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure 2',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP3Text = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure 3',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP4Text = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure 4',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP5Text = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure 5',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ystart;
            xpos = xpos+xsize+xgap*1.5;
            xsize = 90;

            obj.hExtractionReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Voltage [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hEinselReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Voltage [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hExbReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Voltage [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hEsaReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Voltage [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hDeflReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Voltage [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hYsteerReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Voltage [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hFaradayReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Current [A]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hMassReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Flow [sccm]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP1ReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure [torr]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP2ReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure [torr]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP3ReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure [torr]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP4ReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure [torr]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP5ReadText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Pressure [torr]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ystart+2;
            xpos = xpos+xsize;
            xsize = 60;

            obj.hExtractionReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hEinselReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hExbReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hEsaReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hDeflReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hYsteerReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hFaradayReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hMassReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP1ReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP2ReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP3ReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP4ReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hP5ReadField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'Enable','inactive',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ystart-ysize*2-ygap*2;
            xpos = xpos+xsize+xgap;

            obj.hExbSetText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Vset [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hEsaSetText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Vset [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hDeflSetText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Vset [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hYsteerSetText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Vset [V]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize*2-ygap*2;

            obj.hMassSetText = uicontrol(obj.hStatusGrp,'Style','text',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','Fset [%]: ',...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ystart-ysize*2-ygap*2+2;
            xpos = xpos+xsize;

            obj.hExbSetField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hEsaSetField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hDeflSetField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize-ygap;

            obj.hYsteerSetField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ypos-ysize*2-ygap*2;

            obj.hMassSetField = uicontrol(obj.hStatusGrp,'Style','edit',...
                'Position',[xpos,ypos,xsize,ysize],...
                'FontSize',9,...
                'HorizontalAlignment','right');

            ypos = ystart-ysize*2-ygap*2+2;
            xpos = xpos+xsize+10;
            xsize = 50;

            obj.hExbSetBtn = uicontrol(obj.hStatusGrp,'Style','pushbutton',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','SET',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','center');

            ypos = ypos-ysize-ygap;

            obj.hEsaSetBtn = uicontrol(obj.hStatusGrp,'Style','pushbutton',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','SET',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','center');

            ypos = ypos-ysize-ygap;

            obj.hDeflSetBtn = uicontrol(obj.hStatusGrp,'Style','pushbutton',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','SET',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','center');

            ypos = ypos-ysize-ygap;

            obj.hYsteerSetBtn = uicontrol(obj.hStatusGrp,'Style','pushbutton',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','SET',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','center');

            ypos = ypos-ysize*2-ygap*2;

            obj.hMassSetBtn = uicontrol(obj.hStatusGrp,'Style','pushbutton',...
                'Position',[xpos,ypos,xsize,ysize],...
                'String','SET',...
                'FontWeight','bold',...
                'FontSize',9,...
                'HorizontalAlignment','center');

            obj.hFileMenu = uimenu(obj.hFigure,'Text','File');
            set(obj.hFigure,'DockControls','off');

            xmid = 700;
            xgap = 8;
            ystart = 400;
            ypos = ystart;
            ysize = 22;
            ygap = 20;
            xtextsize = 160;
            xeditsize = 180;

            obj.hSequenceText = uicontrol(obj.hFigure,'Style','text',...
                'Position',[xmid-xtextsize-xgap/2,ypos,xtextsize,ysize],...
                'String','Test Sequence:',...
                'FontSize',12,...
                'FontWeight','bold',...
                'HorizontalAlignment','right');

            obj.hSequenceEdit = uicontrol(obj.hFigure,'Style','text',...
                'Position',[xmid+xgap/2,ypos,xeditsize,ysize],...
                'String',num2str(obj.TestSequence),...
                'FontSize',12,...
                'FontWeight','bold',...
                'HorizontalAlignment','left');

            ypos = ypos-ysize-ygap;

            obj.hDateText = uicontrol(obj.hFigure,'Style','text',...
                'Position',[xmid-xtextsize-xgap/2,ypos,xtextsize,ysize],...
                'String','Test Date:',...
                'FontSize',12,...
                'FontWeight','bold',...
                'HorizontalAlignment','right');

            obj.hDateEdit = uicontrol(obj.hFigure,'Style','text',...
                'Position',[xmid+xgap/2,ypos,xeditsize,ysize],...
                'String',obj.TestDate,...
                'FontSize',12,...
                'FontWeight','bold',...
                'HorizontalAlignment','left');
            
            ypos = ypos-ysize-ygap*2;

            obj.hOperatorText = uicontrol(obj.hFigure,'Style','text',...
                'Position',[xmid-xtextsize-xgap/2,ypos,xtextsize,ysize],...
                'String','Test Operator:',...
                'FontSize',12,...
                'FontWeight','bold',...
                'HorizontalAlignment','right');

            obj.hOperatorEdit = uicontrol(obj.hFigure,'Style','popupmenu',...
                'Position',[xmid+xgap/2,ypos,xeditsize,ysize],...
                'String',[{''},obj.OperatorList],...
                'FontSize',11,...
                'HorizontalAlignment','left',...
                'Callback',@obj.operatorCallback);

            ypos = ypos-ysize-ygap;

            obj.hGasText = uicontrol(obj.hFigure,'Style','text',...
                'Position',[xmid-xtextsize-xgap/2,ypos,xtextsize,ysize],...
                'String','Gas Type:',...
                'FontSize',12,...
                'FontWeight','bold',...
                'HorizontalAlignment','right');

            obj.hGasEdit = uicontrol(obj.hFigure,'Style','popupmenu',...
                'Position',[xmid+xgap/2,ypos,xeditsize,ysize],...
                'String',[{''},obj.GasList],...
                'FontSize',11,...
                'HorizontalAlignment','left',...
                'Callback',@obj.gasCallback);

            ypos = ypos-ysize-ygap*2;

            obj.hAcquisitionText = uicontrol(obj.hFigure,'Style','text',...
                'Position',[xmid-xtextsize-xgap/2,ypos,xtextsize,ysize],...
                'String','Acquisition Type:',...
                'FontSize',12,...
                'FontWeight','bold',...
                'HorizontalAlignment','right');

            obj.hAcquisitionEdit = uicontrol(obj.hFigure,'Style','popupmenu',...
                'Position',[xmid+xgap/2,ypos,xeditsize,ysize],...
                'String',[{''},obj.AcquisitionList],...
                'FontSize',11,...
                'HorizontalAlignment','left',...
                'Callback',@obj.acquisitionCallback);
            
            ysize = 66;

            obj.hRunBtn = uicontrol(obj.hFigure,'Style','pushbutton',...
                'Position',[xmid-xtextsize-xgap/2,40,xtextsize+xgap+xeditsize,ysize],...
                'String','RUN TEST',...
                'FontSize',16,...
                'FontWeight','bold',...
                'HorizontalAlignment','center',...
                'Callback',@obj.runTestCallback);


        end

        function operatorCallback(obj,src,~)

            obj.popupBlankDelete(src);
            
            if ~strcmp(src.String{src.Value},"")
                obj.TestOperator = src.String{src.Value};
            end

        end

        function gasCallback(obj,src,~)

            obj.popupBlankDelete(src);

            if ~strcmp(src.String{src.Value},"")
                obj.GasType = src.String{src.Value};
            end

        end

        function acquisitionCallback(obj,src,~)

            obj.popupBlankDelete(src);

            if ~strcmp(src.String{src.Value},"")
                obj.AcquisitionType = src.String{src.Value};
            end

        end

        function runTestCallback(obj,~,~)

            if isempty(obj.TestOperator)
                errordlg('A test operator must be selected before proceeding!','Don''t be lazy!');
                return
            end

            if isempty(obj.GasType)
                errordlg('A gas type must be selected before proceeding!','Don''t be lazy!');
                return
            end

            if isempty(obj.AcquisitionType)
                errordlg('An acquisition type must be selected before proceeding!','Don''t be lazy!');
                return
            end

            obj.genTestSequence;

            set(obj.hSequenceEdit,'String',num2str(obj.TestSequence));
            set(obj.hDateEdit,'String',obj.TestDate);

            acqPath = which(strrep(obj.AcquisitionType,' ',''));
            tokes = regexp(acqPath,'\\','split');
            fcnStr = tokes{end}(1:end-2);
            hFcn = str2func(fcnStr);
            hFcn(obj);
            
        end

    end

    methods (Static, Access = private)

        function popupBlankDelete(src)

            if isempty(src.String{1})
                if src.Value ~= 1
                    oldVal = src.Value;
                    src.String = src.String(2:end);
                    src.Value = oldVal-1;
                else
                    return
                end
            end

        end

    end

end

