function monitors = setupMonitors(instruments)

    function val = read_srsHVPS(self)
        val = self.parent.measV;
    end

    function set_srsHVPS(self,volt)
        if isnan(volt)
            errordlg('A valid voltage value must be entered!','Invalid input!');
            return
        elseif volt > self.parent.VMax || volt < self.parent.VMin
            errordlg(['Defl voltage setpoint must be between ',num2str(hDefl.VMin),' and ',num2str(hDefl.VMax),' V!'],'Invalid input!');
            return
        end    
        self.parent.setVSet(volt);
    end

    function val = read_voltEXB(self)
        HvExbp = self.parent(1);
        HvExbn = self.parent(2);
        val = HvExbp.measV()-HvExbn.measV();
    end
    function set_voltEXB(self,volt)
        HvExbp = self.parent(1);
        HvExbn = self.parent(2);
        HvExbp.setVSet(volt/2);
        HvExbn.setVSet(-volt/2);
    end
    monitors = struct(...       
                 'voltDefl',monitor('readFunc',@read_srsHVPS,...
                                     'setFunc',@set_srsHVPS,...
                                     'textLabel','Defl Voltage',...
                                     'unit','V',...
                                     'active',true,...
                                     'parent',instruments.HvDefl...
                                     ),...
                 'voltXsteer',monitor('readFunc',@read_srsHVPS,...
                                     'setFunc',@set_srsHVPS,...
                                     'textLabel','X-Steer Voltage',...
                                     'unit','V',...
                                     'active',true,...
                                     'parent',instruments.HvEsa...
                                     ),...
                 'voltYsteer',monitor('readFunc',@read_srsHVPS,...
                                     'setFunc',@set_srsHVPS,...
                                     'textLabel','Y-Steer Voltage',...
                                     'unit','V',...
                                     'active',true,...
                                     'parent',instruments.HvYsteer...
                                     ),...
                 'voltExbn',monitor('readFunc',@read_srsHVPS,...
                                     'setFunc',@set_srsHVPS,...
                                     'textLabel','ExB- Voltage',...
                                     'unit','V',...
                                     'active',true,...
                                     'parent',instruments.HvExbn...
                                     ),...
                 'voltExbp',monitor('readFunc',@read_srsHVPS,...
                                     'setFunc',@set_srsHVPS,...
                                     'textLabel','ExB+ Voltage',...
                                     'unit','V',...
                                     'active',true,...
                                     'parent',instruments.HvExbp...
                                     ),...
                 'voltEXB',monitor('readFunc',@read_voltEXB,...
                                     'setFunc',@set_voltEXB,...
                                     'textLabel','ExB Voltage',...
                                     'unit','V',...
                                     'active',true,...
                                     'parent',[instruments.HvExbp,instruments.HvExbn]...
                                     ),...
                 'voltExt',monitor('readFunc',@(x) x.parent.performScan(1,1)*4000,...
                                     'textLabel','Extraction Voltage',...
                                     'unit','V',...
                                     'parent',instruments.keithleyMultimeter1...
                                     ),...
                 'voltLens',monitor('readFunc',@(x) x.parent.performScan(2,2)*1000,...
                                     'textLabel','Lens Voltage',...
                                     'unit','V',...
                                     'parent',instruments.keithleyMultimeter1...
                                     ),...
                 'voltMFC',monitor('readFunc',@(x) x.parent.performScan(3,3),...
                                     'textLabel','MFC Voltage',...
                                     'unit','V',...
                                     'active',false,...
                                     'parent',instruments.keithleyMultimeter1...
                                     ),...
                 'pressureBeamIG1',monitor('readFunc',@(x) x.parent.readPressure(1),...
                                     'textLabel','Beam Pressure (IG1)',...
                                     'unit','T',...
                                     'parent',instruments.leyboldPressure2...
                                     ),...
                 'pressureChamberIG1',monitor('readFunc',@(x) x.parent.readPressure(2),...
                                     'textLabel','Chamber Pressure (IG1)',...
                                     'unit','T',...
                                     'parent',instruments.leyboldPressure2...
                                     ),...
                 'pressureChamberIG2',monitor('readFunc',@(x) x.parent.readPressure(3),...
                                     'textLabel','Beam Pressure (IG2)',...
                                     'unit','T',...
                                     'parent',instruments.leyboldPressure2...
                                     ),...
                 'pressureSourceGas',monitor('readFunc',@(x) x.parent.readPressure(1),...
                                     'textLabel','Source Gas Inflow Pressure',...
                                     'unit','T',...
                                     'parent',instruments.leyboldPressure1...
                                     ),...
                 'pressureBeamRough',monitor('readFunc',@(x) x.parent.readPressure(2),...
                                     'textLabel','Beam Rough Pressure',...
                                     'unit','T',...
                                     'parent',instruments.leyboldPressure1...
                                     )...
                 );

    %assign tags to instrument structures
     fields = fieldnames(monitors);
     for i=1:numel(fields)
         monitors.(fields{i}).setfield('Tag',fields{i});
     end
end